baseURL: "https://ranulv.github.io/" 
title: Ranul Vithanage
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: /cv.pdf
          weight: 1
        - name: Publications
          url: /publications/
          weight: 2
        - name: Experience
          url: /experience/
          weight: 3
        - name: Projects
          url: /projects/
          weight: 4


params:
    description: "I’m a doctoral researcher exploring how humans and robots can better understand each other. My work spans Human-Robot Interaction (HRI), Human-Computer Interaction (HCI), and Tutoring Robots. I investigate how tutoring robots can better adapt to human skills, behaviour and emotional states to build smarter, more responsive learning tools that genuinely help people."
    author: Ranul Vithanage
    googleAnalyticsID:
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ranul Vithanage
          subtitle: "I’m a doctoral researcher exploring how humans and robots can better understand each other. My work spans Human-Robot Interaction (HRI), Human-Computer Interaction (HCI), and Tutoring Robots. I investigate how tutoring robots can better adapt to human skills, behaviour and emotional states to build smarter, more responsive learning tools that genuinely help people."
          imageUrl: "/Ranul.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ranul Vithanage
          buttons:
            - name: CV
              url: /cv.pdf
            - name: Publications
              url: /publications/
            - name: Experience
              url: /experience/
            - name: Projects
              url: /projects/


    socialIcons:
        - name: Email
          url: mailto:r.thalahitiya-vithanage25@imperial.ac.uk
        - name: GitHub
          url: https://github.com/ranulv
        - name: LinkedIn 
          url: https://www.linkedin.com/in/ranul-vithanage/

    assets:
        favicon: /favicon.svg
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Ranul Vithanage"
      icon: /favicon.svg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
