baseURL: "https://ranulv.github.io/" 
title: Ranul Vithanage
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: /publications/
          weight: 1   
        - name: Projects
          url: /projects/
          weight: 2
        - name: Modules
          url: /modules/
          weight: 3


params:
    description: "I am final-year undergraduate studying Mechanical Engineering at the Univeristy of Moratuwa, Sri Lanka. I am passionate about Robotics, Human Computer Interaction, Computer Vision, Autonomous Systems and Artificial Intelligence."
    author: Ranul Vithanage
    googleAnalyticsID:
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ranul Vithanage
          subtitle: "I am final-year undergraduate studying Mechanical Engineering at the Univeristy of Moratuwa, Sri Lanka. I am passionate about Robotics, Human Computer Interaction, Computer Vision, Autonomous Systems and Artificial Intelligence."
          imageUrl: "/Ranul.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ranul Vithanage
          buttons:
            - name: Publications
              url: /publications/        
            - name: Projects
              url: /projects/
            - name: Modules
              url: /modules/


    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:vithanagetvrh.19@uom.lk
        - name: GitHub
          url: https://github.com/ranulv
        - name: LinkedIn 
          url: https://www.linkedin.com/in/ranul-vithanage/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Ranul Vithanage"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
